version: "3"

volumes:
  authdata:
  trainingdata:
  pgadmindata:

services:

  training-postgres:
    image: postgres:alpine
    container_name: training-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=training
      - POSTGRES_PASSWORD=training
      - POSTGRES_DB=training
    volumes:
      - trainingdata:/var/lib/postgresql/data:Z
    ports:
      - "6543:5432"

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    hostname: pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=training@akfc.com
      - PGADMIN_DEFAULT_PASSWORD=training
    volumes:
      - pgadmindata:/var/lib/pgadmin4/storage
    ports:
      - "80:80"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"

  rabbitmq:
    image: bitnami/rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_USERNAME=training
      - RABBITMQ_PASSWORD=training
    ports:
      - "5672:5672"
      - "15672:15672"

